ConstructManSys/ConstructManSys/ConManSysClient/Controllers/ProjectController.cs
using ConManSysClient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ConManSysClient.Controllers
{
    public class ProjectController : Controller
    {
        private ServiceLink ser = new ServiceLink();

        // GET: Project
        public ActionResult Index(int id)
        {
            var p = ser.GetProject(id);
            p.mat = ser.GetAllMaterial(p);
            p.workers = ser.GetAllWorkers(p);

            return View(p);
        }

        // GET: Project/Details/5
        public ActionResult WorkerList(int id)
        {
            var p = ser.GetProject(id);
            var l = ser.GetAllWorkers(p);
            var list = new WorkList();
            list.proj = p;
            list.workList = l;
            return View(list);
        }

        public ActionResult MaterialList(int id)
        {
            var p = ser.GetProject(id);
            var l = ser.GetAllMaterial(p);
            var list = new MatList();
            list.proj = p;
            list.matList = l;
            return View(list);
        }

        public ActionResult Return(int id)
        {
            return RedirectToAction("ProjectList", "Manager", new { id = id });
        }

        public ActionResult HireEmployee(int id)
        {
            var p = ser.GetProject(id);
            var work = new WorkerMod();
            work.proj = p; work.projID = p.id;

            var stat = ser.GetWorkStatus();
            var title = ser.GetWorkTitles();
            foreach (var x in stat)
                work.statusItem.Add(new SelectListItem() { Text = x, Value = x });
            foreach (var x in title)
                work.titleItem.Add(new SelectListItem() { Text = x, Value = x });

            return View(work);
        }

        public ActionResult AddMaterial(int id)
        {
            var p = ser.GetProject(id);
            var nMat = new MaterialMod();
            nMat.proj = p;
            nMat.projID = p.id;

            return View(nMat);
        }

        public ActionResult EditWorker(int id)
        {
            var work = ser.GetWorker(id);
            work.projID = work.proj.id;
            var stat = ser.GetWorkStatus();
            var t = ser.GetWorkTitles();

            foreach (var x in stat)
                work.statusItem.Add(new SelectListItem() { Text = x, Value = x });
            foreach (var x in t)
                work.titleItem.Add(new SelectListItem() { Text = x, Value = x });

            return View(work);
        }

        public ActionResult EditMaterial(int id)
        {
            var mat = ser.GetAllMaterial().FirstOrDefault(x => x.materialID == id);
            mat.projID = mat.proj.id;

            return View(mat);
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult HireEmployee(WorkerMod work)
        {
            try
            {
                var proj = ser.GetProject(work.projID);
                work = ser.MakeWorker(work.first, work.last, work.title, proj, work.status);

                if (work != null)
                    return RedirectToAction("Index", new { id = proj.id });

                throw new Exception();
            }
            catch
            {
                return RedirectToAction("Index", new { id = work.projID });
            }
        }

        [HttpPost]
        public ActionResult AddMaterial(MaterialMod mat)
        {
            try
            {
                var nProj = ser.GetProject(mat.projID);
                var nMat = ser.AddMaterial(mat.name, mat.amntNeed, mat.amntHave, nProj);

                if (nMat != null)
                    return RedirectToAction("Index", new { id = mat.projID });

                throw new Exception();
            }
            catch
            {
                return View(mat);
            }
        }

        [HttpPost]
        public ActionResult EditWorker(WorkerMod work)
        {
            try
            {
                var proj = ser.GetProject(work.projID);
                var w = ser.GetWorker(work.workerID);
                work = ser.UpdateWorker(w, work.first, work.last, work.title, proj, work.status);

                if (work != null)
                    return RedirectToAction("Index", new { id = proj.id });

                throw new Exception();
            }
            catch
            {
                return RedirectToAction("EditWorker", new { id = work.projID });
            }
        }

        [HttpPost]
        public ActionResult EditMaterial(MaterialMod mat)
        {
            try
            {
                var nProj = ser.GetProject(mat.projID);
                var m = ser.GetAllMaterial().FirstOrDefault(x => x.materialID == mat.materialID);
                var nMat = ser.EditMaterial(m, mat.name, mat.amntNeed, mat.amntHave, nProj);

                if (nMat != null)
                    return RedirectToAction("Index", new { id = mat.projID });

                throw new Exception();
            }
            catch
            {
                return View(mat);
            }
        }

        public ActionResult DelMaterial(int id)
        {
            var mat = ser.GetAllMaterial().FirstOrDefault(x => x.materialID == id);
            var proj = mat.proj;

            ser.DelMaterial(mat);

            return RedirectToAction("Index", new { id = proj.id });
        }

        public ActionResult DelWorker(int id)
        {
            var work = ser.GetWorker(id);
            var proj = work.proj;

            ser.DelWorker(work);

            return RedirectToAction("Index", new { id = proj.id });
        }
    }


}

ConstructManSys/ConstructManSys/ConManSysClient/Views/Project/AddMaterial.cshtml
@model ConManSysClient.Models.MaterialMod

@{
    ViewBag.Title = "AddMaterial";
}

<h2>Add Material</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Material</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.projID)


        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amntHave, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amntHave, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
                @Html.ValidationMessageFor(model => model.amntHave, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amntNeed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amntNeed, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
                @Html.ValidationMessageFor(model => model.amntNeed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" /> |
                <a href="@Url.Action("Index", "Project", new { id = Model.projID })" class="btn btn-danger">Cancel</a>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ConstructManSys/ConstructManSys/ConManSysClient/Views/Project/EditMaterial.cshtml
@model ConManSysClient.Models.MaterialMod

@{
    ViewBag.Title = "EditMaterial";
}

<h2>Material</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Html.DisplayFor(model => model.name)</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.projID)
        @Html.HiddenFor(model => model.materialID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amntHave, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amntHave, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
                @Html.ValidationMessageFor(model => model.amntHave, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amntNeed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amntNeed, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
                @Html.ValidationMessageFor(model => model.amntNeed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" /> |
                <a href="@Url.Action("DelMaterial", "Project", new { id = Model.materialID})" class="btn btn-danger">Delete</a> |
                <a href="@Url.Action("Index", "Project", new { id = Model.projID})" class="btn btn-warning">Back</a>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ConstructManSys/ConstructManSys/ConManSysClient/Views/Project/EditWorker.cshtml
@model ConManSysClient.Models.WorkerMod

@{
    ViewBag.Title = "EditWorker";
}

<h2>Worker</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Html.DisplayFor(model => model.first) @Html.DisplayFor(model => model.last)</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.projID)
        @Html.HiddenFor(model => model.workerID)

        <div class="form-group">
            @Html.LabelFor(model => model.first, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.title, Model.titleItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.status, Model.statusItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" /> |
                <a href="@Url.Action("DelWorker", "Project", new { id = Model.workerID})" class="btn btn-danger">Delete</a> |
                <a href="@Url.Action("Index", "Project", new { id = Model.projID})" class="btn btn-warning">Back</a>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ConstructManSys/ConstructManSys/ConManSysClient/Views/Project/HireEmployee.cshtml
@model ConManSysClient.Models.WorkerMod

@{
    ViewBag.Title = "HireEmployee";
}

<h2>Hire Employee</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Worker</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.projID)


        <div class="form-group">
            @Html.LabelFor(model => model.first, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.title, Model.titleItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.status, Model.statusItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" /> |
                <a href="@Url.Action("Index", "Project", new { id = Model.projID })" class="btn btn-danger">Cancel</a>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ConstructManSys/ConstructManSys/ConManSysClient/Views/Project/Index.cshtml
@model ConManSysClient.Models.ProjectMod

@{
    ViewBag.Title = "Index";
}

<style>

circle {
  fill: rgb(31, 119, 180);
  fill-opacity: .25;
  stroke: rgb(31, 119, 180);
  stroke-width: 1px;
}

.work circle {
  fill: orange;
  fill-opacity: 1;
}

.mat circle {
  fill: mediumpurple;
  fill-opacity: 1;
}

text {
  font: 10px sans-serif;
}

</style>

<div>
    <h4>Project</h4>
    <h2>@Html.DisplayFor(model => model.name)</h2>
</div>
<hr />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@Html.HiddenFor(model => model.manager)
@Html.HiddenFor(model => model.id)

<!--<div>
    @Html.ActionLink("Workers", "WorkerList", new { id = Model.id}) |
    @Html.ActionLink("Materials", "MaterialList", new { id = Model.id })
</div>-->

<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#Graph">Diagram</a></li>
    <li><a data-toggle="tab" href="#WorkList">Workers</a></li>
    <li><a data-toggle="tab" href="#MatList">Material</a></li>
</ul>

<div class="tab-content">
    <div id="Graph" class="tab-pane fade in active">
        <div id="projInfo" class="hidden">
        <p id="projName">@Html.Raw(Json.Encode(Model.name))</p>
        <p id="projStatus">@Html.Raw(Json.Encode(Model.status))</p>
        <p id="workList">@Html.Raw(Json.Encode(Model.workers))</p>
        <p id="matList">@Html.Raw(Json.Encode(Model.mat))</p>
        <p id="man">@Html.Raw(Json.Encode(Model.manager))</p>
        </div>

        <div id="graphSec"></div>
    </div>

    <div id="WorkList" class="tab-pane fade">
        <h3>Employees</h3>
        <p>
            <a href="@Url.Action("HireEmployee", "Project", new { id = Model.id })" class="btn btn-primary">New Employee</a>
        </p>

        <table class="table table-hover">
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Title
                </th>
                <th>
                    Worker Status
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.workers)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.first + " " + item.last, "EditWorker", new { id = item.workerID })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.status)
                    </td>
                </tr>
            }

        </table>

    </div>
    <div id="MatList" class="tab-pane fade">
        <h3>Materials</h3>
        <p>
            <a href="@Url.Action("AddMaterial", "Project", new { id = Model.id })" class="btn btn-primary">New Material</a>
        </p>

        <table class="table table-hover">
            <tr>
                <th>
                    @Html.DisplayName("Material")
                </th>
                <th>
                    @Html.DisplayName("Quantity Available")
                </th>
                <th>
                    @Html.DisplayName("Quantity Needed")
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.mat)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.name, "EditMaterial", new { id = item.materialID})
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.amntHave, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.amntNeed, new { htmlAttributes = new { @class = "form-control", @type = "number", @min = "0" } })
                    </td>
                    <td>
                        <a href="@Url.Action("DelMaterial", "Project", new { id = item.materialID})" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            }

        </table>

    </div>
</div>

<div>
    <a href="@Url.Action("ProjectList", "Manager", new { id = Model.manager.managerID })" class="btn btn-warning">Return</a>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
@Scripts.Render("~/bundle/graph-scripts")

ConstructManSys/ConstructManSys/ConManSysClient/Views/Project/MaterialList.cshtml
@model ConManSysClient.Models.MatList

@{
    ViewBag.Title = "MaterialList";
}

<h2>Material List</h2>

<p>
    @Html.ActionLink("New Material", "AddMaterial", new { id = Model.proj.id })
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayName("Material Name")
        </th>
        <th>
            @Html.DisplayName("Quantity Available")
        </th>
        <th>
            @Html.DisplayName("Quantity Needed")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.matList) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amntHave)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amntNeed)
        </td>
        <td>
            @Html.ActionLink("Details", "EditMaterial", new { id = item.materialID }) 
        </td>
    </tr>
}

</table>


<div>
    @Html.ActionLink("Back", "Index", new { id = Model.proj.id })
</div>

ConstructManSys/ConstructManSys/ConManSysClient/Views/Project/WorkerList.cshtml
@model ConManSysClient.Models.WorkList

@{
    ViewBag.Title = "WorkerList";
}

<h2>Worker List</h2>

<p>
    @Html.ActionLink("New Employee", "HireEmployee", new { id = Model.proj.id })
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayName("FirstName")
        </th>
        <th>
            @Html.DisplayName("LastName")
        </th>
        <th>
            @Html.DisplayName("Title")
        </th>
        <th>
            @Html.DisplayName("Worker Status")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.workList) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.first)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.last)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <td>
            @Html.ActionLink("Details", "EditWorker", new { id = item.workerID })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back", "Index", new { id = Model.proj.id})
</div>