ConstructManSys/ConstructManSys/ConManSysClient/Controllers/ManagerController.cs
using ConManSysClient.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ConManSysClient.Controllers
{
    public class ManagerController : Controller
    {

        private ServiceLink ser = new ServiceLink();

        public ActionResult Index(int id)
        {
            return RedirectToAction("Index", "Project", new { id = id });
        }

        // GET: Manager
        public ActionResult ProjectList(int id)
        {
            var man = ser.GetManager(id);
            ProjList list = new ProjList();
            list.projList = ser.GetProjectByManager(man);
            list.man = man;
            return View(list);
        }

        // GET: Manager/Create
        public ActionResult CreateProject(int id)
        {
            ProjectMod proj = new ProjectMod();
            var stat = ser.GetProjectStatus();
            foreach (var x in stat)
            {
                proj.statusItem.Add(new SelectListItem()
                {
                    Text = x,
                    Value = x
                });
            }
            return View(new newProj() { manID = id, nProj = proj });
        }

        // POST: Manager/Create
        [HttpPost]
        public ActionResult CreateProject(newProj proj)
        {
            try
            {
                var man = ser.GetManager(proj.manID);
                var nProj = ser.MakeProject(proj.nProj.name, proj.nProj.start, proj.nProj.end, proj.nProj.status, man);
                if (nProj != null)
                    return RedirectToAction("ProjectList", new { id = man.managerID });


                throw new Exception();
            }
            catch
            {
                return RedirectToAction("CreateProject", new { id = proj.man.managerID });
            }
        }

        public ActionResult EditManager(int id)
        {
            var man = ser.GetManager(id);
            return View(man);
        }

        [HttpPost]
        public ActionResult EditManager(ManagerMod man)
        {
            var temp = ser.GetManager(man.managerID);
            man = ser.UpdateManager(temp, man.FirstName, man.LastName, man.UserName, man.Password);
            return RedirectToAction("ProjectList", new { id = man.managerID });
        }

        public ActionResult EditProject(int id)
        {
            ProjectMod nProj = ser.GetProject(id);
            var stat = ser.GetProjectStatus();
            foreach (var x in stat)
            {
                nProj.statusItem.Add(new SelectListItem()
                {
                    Text = x,
                    Value = x
                });
            }
            return View(nProj);
        }

        [HttpPost]
        public ActionResult EditProject(ProjectMod proj)
        {
            var p = ser.GetProject(proj.id);
            var temp = ser.UpdateProject(p, proj.name, proj.start, proj.end, proj.status, p.manager);

            return RedirectToAction("ProjectList", new { id = p.manager.managerID });
        }

        // GET: Manager/Delete/5
        public ActionResult DelProject(int id)
        {
            var proj = ser.GetProject(id);
            return View(proj);
        }

        [HttpPost, ActionName("DelProject")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                var p = ser.GetProject(id);
                var man = ser.GetManager(p.manager.managerID);
                ser.DeleteProject(p);
                return RedirectToAction("ProjectList", new { id = man.managerID });
            }
            catch
            {
                return View();
            }
        }
    }
}

ConstructManSys/ConstructManSys/ConManSysClient/Views/Manager/CreateProject.cshtml
@model ConManSysClient.Models.newProj

@{
    ViewBag.Title = "CreateProject";
}

<h2>Create Project</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.manID)
        <div class="hidden">Model.manID</div>


        <div class="form-group">
            @Html.LabelFor(model => model.nProj.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nProj.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nProj.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nProj.start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nProj.start, new { htmlAttributes = new { @class = "form-control", @id="dateStart" } })
                @Html.ValidationMessageFor(model => model.nProj.start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nProj.end, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nProj.end, new { htmlAttributes = new { @class = "form-control", @id="dateEnd" } })
                @Html.ValidationMessageFor(model => model.nProj.end, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nProj.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.nProj.status, Model.nProj.statusItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nProj.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info" /> |
                <a href="@Url.Action("ProjectList", "Manager", new { id = Model.manID})" class="btn btn-warning">Back</a> 
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/scripts/bootstrap-datepicker.js"></script>

<script>
    $.fn.datepicker.defaults.format = "mm/dd/yyyy";
    var s = $("#dateStart").datepicker({
        startDate: '-3d'
    }).on('changeDate', function (ev) {
        if (ev.date.valueOf() > e.date.valueOf()) {
            var newDate = new Date(ev.date)
            newDate.setDate(newDate.getDate() + 1);
            e.setValue(newDate);
        }
        s.hide();
        $('#dateEnd')[0].focus();
    }).data('datepicker');


    var e = $("#dateEnd").datepicker({
        startDate: '-2d',
        onRender: function (date) {
            return date.valueOf() <= s.date.valueOf() ? 'disabled' : '';
        }
    }).on('changeDate', function (ev) {
        e.hide();
    }).data('datepicker');
</script>

ConstructManSys/ConstructManSys/ConManSysClient/Views/Manager/DelProject.cshtml
@model ConManSysClient.Models.ProjectMod

@{
    ViewBag.Title = "DelProject";
}

<h2>Delete Project</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProjectMod</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.start)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.start)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.end)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.end)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a href="@Url.Action("ProjectList", "Manager", new { id = Model.manager.managerID})" class="btn btn-info">Cancel</a>
        </div>
    }
</div>

ConstructManSys/ConstructManSys/ConManSysClient/Views/Manager/EditManager.cshtml
@model ConManSysClient.Models.ManagerMod

@{
    ViewBag.Title = "EditManager";
}

<h2>EditManager</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ManagerMod</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.managerID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" /> |
                <a href="@Url.Action("ProjectList", "Manager", new { id = Model.managerID})" class="btn btn-warning">Cancel</a> 
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ConstructManSys/ConstructManSys/ConManSysClient/Views/Manager/EditProject.cshtml
@model ConManSysClient.Models.ProjectMod

@{
    ViewBag.Title = "EditProject";
}

<h2>Edit Project</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.manager)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.start, new { htmlAttributes = new { @class = "form-control", @id = "dateStart" } })
                @Html.ValidationMessageFor(model => model.start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.end, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.end, new { htmlAttributes = new { @class = "form-control", @id = "dateEnd" } })
                @Html.ValidationMessageFor(model => model.end, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.status, Model.statusItem, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" /> | 
                <a href="@Url.Action("ProjectList", "Manager", new { id = Model.manager.managerID })" class="btn btn-warning">Back</a>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/scripts/bootstrap-datepicker.js"></script>

<script>
    $.fn.datepicker.defaults.format = "mm/dd/yyyy";
    var s = $("#dateStart").datepicker({
        startDate: '-3d'
    }).on('changeDate', function (ev) {
        if (ev.date.valueOf() > e.date.valueOf()) {
            var newDate = new Date(ev.date)
            newDate.setDate(newDate.getDate() + 1);
            e.setValue(newDate);
        }
        s.hide();
        $('#dateEnd')[0].focus();
    }).data('datepicker');


    var e = $("#dateEnd").datepicker({
        onRender: function (date) {
            return date.valueOf() <= s.date.valueOf() ? 'disabled' : '';
        }
    }).on('changeDate', function (ev) {
        e.hide();
    }).data('datepicker');
</script>

ConstructManSys/ConstructManSys/ConManSysClient/Views/Manager/ProjectList.cshtml
@model ConManSysClient.Models.ProjList

@{
    ViewBag.Title = "ProjectList";
}

<div>
    <h2>
        @Html.DisplayFor(model => model.man.FirstName) @Html.DisplayFor(model => model.man.LastName) |
        <a href="@Url.Action("EditManager", "Manager", new { id = Model.man.managerID } )" class="btn btn-info">Settings</a>
    </h2>
</div>



<p>
    <h3>Projects | <a href="@Url.Action("CreateProject", "Manager", new { id = Model.man.managerID } )" class="btn btn-primary">New Project</a> </h3>
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayName("Project Name")
        </th>
        <th>
            @Html.DisplayName("Start Date")
        </th>
        <th>
            @Html.DisplayName("End Date")
        </th>
        <th>
            @Html.DisplayName("Status")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.projList) {
    <tr>
        <td>
            @Html.ActionLink(item.name, "Index", new { id = item.id })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.start)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.end)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <td>
            <a href="@Url.Action("EditProject", "Manager", new { id = item.id})" class="btn btn-warning">Edit</a> |
            <a href="@Url.Action("DelProject", "Manager", new { id = item.id})" class="btn btn-danger">Delete</a>
        </td>
    </tr>
}

</table>

<div>
    <a href="@Url.Action("Login", "Home")" class="btn btn-warning">Logout</a>
</div>